apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    env: test
  namespace: testns   # specific namespace
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 512Mi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"