apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 512Mi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"
  initContainers:
  - name: containerWhichRunFirst
    image: busybox
    command:
      - | 
      sh -c "for i in 1 2 3 4 5
        do 
          sleep 1s 
          echo `Waiting for $i s`
        done"
  nodeSelector:
    disktype: ssd