apiVersion: batch/v1
kind: Job
metadata:
  name: myjob2
spec:
  parallelism: 2
  completions: 10
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(20)"]
      restartPolicy: Never
  backoffLimit: 4