FROM ubuntu


RUN echo "This is the command will run in build time"


COPY ./run-time-script.sh /
RUN chmod +x /run-time-script.sh


# entrypoint is for when running with docker run <image-id> <param>
#ENTRYPOINT ["tail", "-f", "/dev/null"]


# cmd is for when running with docker run <image-id>
CMD ["sh", "/run-time-script.sh"]