apiVersion: v1
kind: Pod
metadata:
  name: adminer
  labels:
    app: adminer
  namespace: adminer   # specific namespace
spec:
  containers:
  - name: adminer
    image: adminer
    imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: adminer-svc
  namespace: adminer
spec:
  type: NodePort
  selector:
    app: adminer
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30008