apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-sts
  namespace: taa
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mysqldb
        image: mysql
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: taa-cfm
              key: db_user
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: taa-cfm
              key: db_name
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: taa-cfm
              key: db_pass
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: taa-cfm
              key: db_pass
        

