apiVersion: apps/v1
kind: Deployment
metadata:
  name: taa-deployment
  namespace: taa
  labels:
    app: taa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: taa
  template:
    metadata:
      labels:
        app: taa
    spec:
      containers:
      - name: my-php-fpm
        image: kumcp1/k8s-php-fpm
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          value: db-svc.taa
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: taa-cfm
              key: db_name
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: taa-cfm
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: taa-cfm
              key: db_pass
      - name: mynginx
        image: kumcp1/k8s-nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80