apiVersion: v1
kind: PersistentVolume
metadata:
  name: taa-pv
  labels:
    type: pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
