apiVersion: v1
kind: Service
metadata:
  name: taa-db-service
  namespace: taa
  labels:
    app: taa-db
spec:
  type: ClusterIP
  selector:
    app: taa-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306