apiVersion: v1
kind: Service
metadata:
  name: taa-service
  namespace: taa
  labels:
    app: taa
spec:
  type: NodePort
  selector:
    app: taa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000